### PR TITLE
+Repository Overview

### PR DESCRIPTION
**Pull request by jedie**
Note: will be copied from: https://github.com/pypyjs/pypyjs/blob/master/README.dist.rst ;)

### CODE REVIEW

**Comment by jedie** [comment]
I didn't have write access here, too... ;)

**Comment by rfk** [comment]
Cool, thanks.  Not sure why I can't auto-merge this, does it conflict somehow?

Anyways, I fixed up the access on those two repos, sorry about that.  I keep forgetting that I have to add the "collaborators" team on new repos.

**Comment by jedie** [comment]
Oh, sorry, no mere needed, because of: https://github.com/pypyjs/pypyjs-release-nojit/commit/a157ff9d8e8f16da7ecb84d183da95f8106a8a5d ;)

**Comment by jedie** [comment]
@rfk : btw. can you activate "issues" on https://github.com/pypyjs/pypyjs-examples please?

**Comment by rfk** [comment]
> can you activate "issues" on https://github.com/pypyjs/pypyjs-examples please?

done :-)

**Pull request closed without merging**
